build: false
environment:
  matrix:
    - PYTHON: "C:/Python27"
      TOXENV: "py27-unittests"
    - PYTHON: "C:/Python33"
      TOXENV: "py33-unittests"
    - PYTHON: "C:/Python34"
      TOXENV: "py34-unittests"
    - PYTHON: "C:/Python27"
      NODEJS: "0.12"
      TOXENV: "lint"
init:
  - "ECHO %TOXENV%"
  - "ECHO %PYTHON%"
  - ps: "ls C:/Python*"
install:
  - ps: (new-object net.webclient).DownloadFile('https://raw.github.com/pypa/pip/master/contrib/get-pip.py', 'C:/get-pip.py')
  - ps: if($env:TOXENV -eq "lint") {Update-NodeJsInstallation $env:NODEJS}
  - if "%TOXENV%" == "lint" npm install -g jshint
  - "%PYTHON%/python.exe C:/get-pip.py"
  - "%PYTHON%/Scripts/pip.exe install virtualenv"
  - "%PYTHON%/Scripts/pip.exe install tox"
  - "%PYTHON%/Scripts/pip.exe install pep257"
test_script:
  - "%PYTHON%/Scripts/pip --version"
  - "%PYTHON%/Scripts/virtualenv.exe --version"
  - "%PYTHON%/Scripts/tox --version"
  - "%PYTHON%/Scripts/tox"
  - if "%TOXENV%" == "lint" jshint .
matrix:
  fast_finish: true
