site_name: PyMdown Documentation
site_url: https://facelessuser.github.io/PyMdown
repo_url: https://github.com/facelessuser/PyMdown
edit_uri: tree/master/docs/src/markdown
site_description: A Python Markdown Preview and Converter Tool
copyright: |
  Copyright &copy; 2014 - 2017 <a href="https://github.com/facelessuser">Isaac Muse</a>
  <br><span class="md-footer-custom-text">emoji provided free by </span><a href="http://www.emojione.com">EmojiOne</a>

theme: material
docs_dir: docs/src/markdown
theme_dir: docs/theme

pages:
  - Home: index.md
  - User Guide:
    - Installation: user-guide/installation.md
    - Markdown Syntax: user-guide/markdown-syntax.md
    - General Usage: user-guide/general-usage.md
    - Pygments Customization: user-guide/pygments-customization.md
  - Contributing &amp; Suppport: contributing.md
  - License: license.md

markdown_extensions:
  - markdown.extensions.toc:
      slugify: !!python/name:pymdownx.slugs.uslugify
      permalink: "\ue157"
  - markdown.extensions.admonition:
  - markdown.extensions.smarty:
      smart_quotes: false
  - pymdownx.betterem:
  - markdown.extensions.attr_list:
  - markdown.extensions.def_list:
  - markdown.extensions.tables:
  - markdown.extensions.abbr:
  - pymdownx.extrarawhtml:
  - pymdownx.superfences:
  - pymdownx.highlight:
      css_class: codehilite
      extend_pygments_lang:
        - name: php-inline
          lang: php
          options:
            startinline: true
  - pymdownx.inlinehilite:
  - pymdownx.magiclink:
      repo_url_shortener: true
      base_repo_url: https://github.com/facelessuser/PyMdown
  - pymdownx.tilde:
  - pymdownx.caret:
  - pymdownx.smartsymbols:
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.escapeall:
      hardbreak: True
      nbsp: True
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.progressbar:
  - pymdownx.arithmatex:
  - pymdownx.mark:
  - pymdownx.plainhtml:
      strip_attributes: ''
  - pymdownx.snippets:
      base_path: docs/src/markdown/_snippets
  - pymdownx.keys:
      separator: "\uff0b"
  - pymdownx.details:

extra:
  logo:
    icon: description
  palette:
    primary: blue
    accent: blue
  font:
    text: Roboto
    code: Roboto Mono
  social:
    - type: github
      link: https://github.com/facelessuser
extra_css:
  - extra-00833721db.css
  - doctable.css
extra_javascript:
  - extra-4596f9831a.js
