site_name: PyMdown Documentation
repo_url: https://github.com/facelessuser/PyMdown
site_description: A Python Markdown Preview and Converter Tool
copyright: Copyright &copy; 2014 - 2015 <a href="https://github.com/facelessuser">Isaac Muse</a>
pages:
  - Home: index.md
  - User Guide:
    - Installation: user-guide/installation.md
    - Markdown Syntax: user-guide/markdown-syntax.md
    - General Usage: user-guide/general-usage.md
    - Pygments Customization: user-guide/pygments-customization.md
    - PyMdown Extensions: user-guide/pymdown-extensions.md
  - Extensions:
    - B64: extensions/b64.md
    - BetterEm: extensions/betterem.md
    - Caret: extensions/caret.md
    - Critic: extensions/critic.md
    - Github: extensions/github.md
    - GithubEmoji: extensions/githubemoji.md
    - HeaderAnchor: extensions/headeranchor.md
    - InlineHilite: extensions/inlinehilite.md
    - MagicLink: extensions/magiclink.md
    - Mark: extensions/mark.md
    - Math: extensions/math.md
    - PathConverter: extensions/pathconverter.md
    - PlainHtml: extensions/plainhtml.md
    - ProgressBar: extensions/progressbar.md
    - PyMdown: extensions/pymdown.md
    - SmartSymbols: extensions/smartsymbols.md
    - SuperFences: extensions/superfences.md
    - Tasklist: extensions/tasklist.md
    - Tilde: extensions/tilde.md
  - Contributing &amp; Suppport: contributing.md
  - License: license.md
theme: readthedocs
theme_dir: doc_theme
markdown_extensions:
  - markdown.extensions.toc
  - markdown.extensions.extra
  - markdown.extensions.admonition
  - markdown.extensions.smarty
  - markdown.extensions.nl2br
  - markdown.extensions.codehilite:
      guess_lang: false
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.betterem
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.smartsymbols
  - pymdownx.githubemoji
  - pymdownx.tasklist
  - pymdownx.superfences
  - pymdownx.progressbar
  - pymdownx.headeranchor
  - pymdownx.math
  - pymdownx.critic
